### ISSUE TITLE
全默认值变量，试了VMESS+WS不通呀！

### ISSUE THREAD

**Issue by rkygogo** [wy580477/PaaS-vmess-trojan-argo#2]
全默认值变量，试了VMESS+WS+tls不通呀！

**Comment by wy580477** [comment]
是所有协议都不通，还是只有tls不通

**Comment by rkygogo** [comment]
> 是所有协议都不通，还是只有tls不通

workers显示200 OK，打开反代地址是空白页面，自定义域也试了，VLESS与VMESS所有协议设置都不通

**Comment by wy580477** [comment]
> > 是所有协议都不通，还是只有tls不通
> 
> workers显示200 OK，打开反代地址是空白页面，自定义域也试了，VLESS与VMESS所有协议设置都不通

1. 我这里没有vless协议。
2. 检查路径，注意变量里面的路径只是前缀。
3. cloudflare中转可能会遇到sni阻断问题，可以尝试80端口无tls协议。
