### ISSUE TITLE
ss+ws不通。

### ISSUE THREAD

**Issue by rkygogo** [wy580477/PaaS-vmess-trojan-argo#3]
别的协议没问题，但ss+ws不通，安卓APP用https://github.com/shadowsocks/shadowsocks-android还是用SagerNet？插件是用xray-plugin？还是用V2ray-plugin？都试了下都不通。。。

**Comment by wy580477** [comment]
之前只在v2ray核心上测试过ss+ws是通的，我这里也不清楚为啥ss+v2ray-plugin不通。

考虑到ss过ws以后对比vmess没有任何优势，我自己也不用这个协议，不投入精力去深究了。

Shadowsocks WS 协议已移除。
