### ISSUE TITLE
按步骤操作，部署失败

### ISSUE THREAD

**Issue by just4somefun** [wy580477/PaaS-vmess-trojan-argo#4]
codespace里操作均无报错，但回到Patr上部署不成功，检查docker repository里面images是空的，好像是没有拉取到docker镜像

**Comment by wy580477** [comment]
> codespace里操作均无报错，但回到Patr上部署不成功，检查docker repository里面images是空的，好像是没有拉取到docker镜像

Patr应该是出故障了，注册个dockerhub账户，网上搜一下推送dockerhub教程，在codespace里面推送到dockerhub上再部署吧。。

现在懒得改README，等过几天看看Patr能不能修好。

**Comment by just4somefun** [comment]
> > codespace里操作均无报错，但回到Patr上部署不成功，检查docker repository里面images是空的，好像是没有拉取到docker镜像
> 
> Patr应该是出故障了，注册个dockerhub账户，网上搜一下推送dockerhub教程，在codespace里面推送到dockerhub上再部署吧。。
> 
> 现在懒得改README，等过几天看看Patr能不能修好。
是否这项目的dokcerhub仓库地址已经被Patr拉黑了？
你意思是让我把你的dockehub镜像推送到我自己的dockerhub上，然后再去Patr上尝试部署是吗？

**Comment by wy580477** [comment]
> 是否这项目的dokcerhub仓库地址已经被Patr拉黑了？

不是，这项目没用 docker hub，README 里面部署步骤是直接推送到 Patr 上的。应该是 Patr 那边出了一些故障。

> > 你意思是让我把你的dockehub镜像推送到我自己的dockerhub上，然后再去Patr上尝试部署是吗？

对，就是这样。部署以后会一直显示 Deploying，但事实上可以用了。Patr 网站现在很多功能都用不了，我尝试走 CI/CD 也拉不到仓库内容。

**Comment by t-e-s-tweb** [comment]
Is it working on patr yet? Mine stopped yesterday and can't get it to work anymore. Not even other docker apps load.

**Comment by wy580477** [comment]
> Is it working on patr yet? Mine stopped yesterday and can't get it to work anymore. Not even other docker apps load.

Patr is not working properly right now. It's not my repo's problem.

**Comment by just4somefun** [comment]
> > 是否这项目的dokcerhub仓库地址已经被Patr拉黑了？
> 
> 不是，这项目没用 docker hub，README 里面部署步骤是直接推送到 Patr 上的。应该是 Patr 那边出了一些故障。
> 
> > > 你意思是让我把你的dockehub镜像推送到我自己的dockerhub上，然后再去Patr上尝试部署是吗？
> 
> 对，就是这样。部署以后会一直显示 Deploying，但事实上可以用了。Patr 网站现在很多功能都用不了，我尝试走 CI/CD 也拉不到仓库内容。

按你的指点，我在codespace里把镜像推送到自己的dockerhub上，再尝试部署后，访问Patr给的URL报错503, 
Depolyment菜单下Image History里面也是空的。

**Comment by wy580477** [comment]
> > > 是否这项目的dokcerhub仓库地址已经被Patr拉黑了？
> > 
> > 
> > 不是，这项目没用 docker hub，README 里面部署步骤是直接推送到 Patr 上的。应该是 Patr 那边出了一些故障。
> > > > 你意思是让我把你的dockehub镜像推送到我自己的dockerhub上，然后再去Patr上尝试部署是吗？
> > 
> > 
> > 对，就是这样。部署以后会一直显示 Deploying，但事实上可以用了。Patr 网站现在很多功能都用不了，我尝试走 CI/CD 也拉不到仓库内容。
> 
> 按你的指点，我在codespace里把镜像推送到自己的dockerhub上，再尝试部署后，访问Patr给的URL报错503, Depolyment菜单下Image History里面也是空的。

我今天试过其它项目也是这样，大概是Patr真的故障了。先折腾别的平台吧。。

**Comment by t-e-s-tweb** [comment]
Others are working fine.  Can you mention some that you use?

**Comment by just4somefun** [comment]
> > > > 是否这项目的dokcerhub仓库地址已经被Patr拉黑了？
> > > 
> > > 
> > > 不是，这项目没用 docker hub，README 里面部署步骤是直接推送到 Patr 上的。应该是 Patr 那边出了一些故障。
> > > > > 你意思是让我把你的dockehub镜像推送到我自己的dockerhub上，然后再去Patr上尝试部署是吗？
> > > 
> > > 
> > > 对，就是这样。部署以后会一直显示 Deploying，但事实上可以用了。Patr 网站现在很多功能都用不了，我尝试走 CI/CD 也拉不到仓库内容。
> > 
> > 
> > 按你的指点，我在codespace里把镜像推送到自己的dockerhub上，再尝试部署后，访问Patr给的URL报错503, Depolyment菜单下Image History里面也是空的。
> 
> 我今天试过其它项目也是这样，大概是Patr真的故障了。先折腾别的平台吧。。

好的，谢谢了。

**Comment by wy580477** [comment]
> Others are working fine. Can you mention some that you use?

Doprax is eazy to deploy and no bandwidth usage limit.

**Comment by t-e-s-tweb** [comment]
Current versions of using wgcf isn't working. I tried multiple times but the error that I get in logs is bad request. Only northflank worked for a while but v2ng still shows timeout error but browsing worked but very slow. 

Does all traffic go through tor?

**Comment by wy580477** [comment]
> Current versions of using wgcf isn't working. 

Is it totally not working? Or just WARP outbound?

> I tried multiple times but the error that I get in logs is bad request. Only northflank worked for a while but v2ng still shows timeout error but browsing worked but very slow.

I did test on Heroku and Render.

On heroku, it's nearly 200mbps.
![image](https://user-images.githubusercontent.com/98247050/216895110-69dd3074-9979-4ea2-afbf-2bd28f35fb1a.png)
On Render, it's very slow due to 0.1 cpu limit.
![image](https://user-images.githubusercontent.com/98247050/216895284-7ac682a9-7a78-4711-9a10-3694430184d9.png)

> Does all traffic go through tor?

No, WARP outbound sometimes is unstable. I'm investigating.

**Comment by t-e-s-tweb** [comment]
<a href="https://ibb.co/W5JP0Sb"><img src="https://i.ibb.co/GpSt9gK/Screenshot-2023-02-07-12-32-12-237-edit-com-android-chrome.jpg" alt="Screenshot-2023-02-07-12-32-12-237-edit-com-android-chrome" border="0"></a>

**Comment by wy580477** [comment]
> [![Screenshot-2023-02-07-12-32-12-237-edit-com-android-chrome](https://camo.githubusercontent.com/2ef014f2245d9f4aa328bb4bae28d625bfd0fc916e565e0e6332e1dc507ce008/68747470733a2f2f692e6962622e636f2f4770537439674b2f53637265656e73686f742d323032332d30322d30372d31322d33322d31322d3233372d656469742d636f6d2d616e64726f69642d6368726f6d652e6a7067)](https://ibb.co/W5JP0Sb)

I fixed a bug which causes vmess inbound not working. Try again with new code.

https://github.com/wy580477/PaaS-vmess-trojan-argo/commit/6323472993ffe65f726adeb80dc21b542ec82985

**Comment by t-e-s-tweb** [comment]
> > [![Screenshot-2023-02-07-12-32-12-237-edit-com-android-chrome](https://camo.githubusercontent.com/2ef014f2245d9f4aa328bb4bae28d625bfd0fc916e565e0e6332e1dc507ce008/68747470733a2f2f692e6962622e636f2f4770537439674b2f53637265656e73686f742d323032332d30322d30372d31322d33322d31322d3233372d656469742d636f6d2d616e64726f69642d6368726f6d652e6a7067)](https://ibb.co/W5JP0Sb)
> 
> I fixed a bug which causes vmess inbound not working. Try again with new code.
> 
> [6323472](https://github.com/wy580477/PaaS-vmess-trojan-argo/commit/6323472993ffe65f726adeb80dc21b542ec82985)

This was run after merging the new code. I was watching your repo and tried it with the new code.

**Comment by wy580477** [comment]
> This was run after merging the new code. I was watching your repo and tried it with the new code.

Which platform are you on?

**Comment by t-e-s-tweb** [comment]
> > This was run after merging the new code. I was watching your repo and tried it with the new code.
> 
> Which platform are you on?

This was run on koyeb.

**Comment by wy580477** [comment]
> > > This was run after merging the new code. I was watching your repo and tried it with the new code.
> > 
> > 
> > Which platform are you on?
> 
> This was run on koyeb.

Now it should be working.  https://github.com/wy580477/PaaS-vmess-trojan-argo/commit/40b3f3d1bc79eb9d9119404c08391237a852c68b

I only tested wireguard config. Forget to change normal config.

**Comment by t-e-s-tweb** [comment]
> > > > This was run after merging the new code. I was watching your repo and tried it with the new code.
> > > 
> > > 
> > > Which platform are you on?
> > 
> > 
> > This was run on koyeb.
> 
> Now it should be working. [40b3f3d](https://github.com/wy580477/PaaS-vmess-trojan-argo/commit/40b3f3d1bc79eb9d9119404c08391237a852c68b)
> 
> I only tested wireguard config. Forget to change normal config.

Didn't work. Trojan works on koyeb pretty fast. Trojan on northflank is super slow. Vmess still doesn't work on both.

**Comment by wy580477** [comment]
> Didn't work. Trojan works on koyeb pretty fast. Trojan on northflank is super slow. Vmess still doesn't work on both.

Then I'm out of idea. On my koyeb deployment, Vmess inbound works fine after fix. 

You can't just say it's not working without any log and details, then expect me to know where to look at.

**Comment by t-e-s-tweb** [comment]
Are you deploying from git or ghr container? And which app are you using as client?

**Comment by wy580477** [comment]
> Are you deploying from git or ghr container? And which app are you using as client?

Why you are asking me instead of providing your setup details? I won't reply any more.

**Comment by wy580477** [comment]
Now I found out it's a problem from sing-box core. Main branch switches back to Xray-core for now
