### ISSUE TITLE
可以设置仅ipv4吗？

### ISSUE THREAD

**Issue by JJins** [wy580477/PaaS-vmess-trojan-argo#5]
如题，另外，部署在render上被秒封，不懂是啥情况，薅azure web app就疯狂断连

**Comment by wy580477** [comment]
> 如题，另外，部署在render上被秒封，不懂是啥情况，薅azure web app就疯狂断连

仅ipv4是什么意思？warp么？不设置WG_IP6_ADDR, warp就只有v4了。

render封号我也搞不太明白，用同一个库部署的，有的存活有的就不行。
建议把readme删掉，一定要用新库，不要用fork的库，注册和部署时候都用干净ip，可能会有作用。

azure web app 怎么撸？求指教。

**Comment by JJins** [comment]
> > 如题，另外，部署在render上被秒封，不懂是啥情况，薅azure web app就疯狂断连
> 
> 仅ipv4是什么意思？warp么？不设置WG_IP6_ADDR, warp就只有v4了。
> 
> render封号我也搞不太明白，用同一个库部署的，有的存活有的就不行。 建议把readme删掉，一定要用新库，不要用fork的库，注册和部署时候都用干净ip，可能会有作用。
> 
> azure web app 怎么撸？求指教。

就是普通的vmess，看后台日志有解析到v6的ip，如果客户端不支持v6会导致断连吗？

azure的话用webapp可以创建免费的docker实例，用你教程里写的pull image的方式部署，但是断连相当严重

**Comment by wy580477** [comment]
> > > 如题，另外，部署在render上被秒封，不懂是啥情况，薅azure web app就疯狂断连
> > 
> > 
> > 仅ipv4是什么意思？warp么？不设置WG_IP6_ADDR, warp就只有v4了。
> > render封号我也搞不太明白，用同一个库部署的，有的存活有的就不行。 建议把readme删掉，一定要用新库，不要用fork的库，注册和部署时候都用干净ip，可能会有作用。
> > azure web app 怎么撸？求指教。
> 
> 就是普通的vmess，看后台日志有解析到v6的ip，如果客户端不支持v6会导致断连吗？

不会，出站设置了domainStrategy: UseIPv4，只会用v4地址连接。

> azure的话用webapp可以创建免费的docker实例，用你教程里写的pull image的方式部署，但是断连相当严重

vmess 和 trojan 都断嘛？之前singbox核心的vmess有问题，前几天换回xray核心了。

**Comment by JJins** [comment]
> 

都断，不过我不懂怎么看默认的配置文件

**Comment by wy580477** [comment]
> > 
> 
> 都断，不过我不懂怎么看默认的配置文件

那试试用cloudflared隧道，如果不断了那可能就是azure web app 入口http路由对websocket长连接有限制。

**Comment by JJins** [comment]
感谢，以前没用过这个，试试看

**Comment by JJins** [comment]
换tunnul+vm后很稳定，再也没断过，跟v6没关系，就是这个原因

> 
> 那试试用cloudflared隧道，如果不断了那可能就是azure web app 入口http路由对websocket长连接有限制。

**Comment by t-e-s-tweb** [comment]
> After switching to tunnel+vm, it is very stable and has never been broken again. It has nothing to do with v6, that’s why
> 
> > Then try to use the cloudflared tunnel. If it continues, it may be that the http routing of the azure web app entry has restrictions on the long-term connection of the websocket.

Are you using it on render? Is it working?

**Comment by JJins** [comment]
Working but no, after deploying this image render removed my account.

________________________________
发件人: t-e-s-tweb ***@***.***>
发送时间: Sunday, February 26, 2023 6:24:17 AM
收件人: wy580477/PaaS-vmess-trojan-argo ***@***.***>
抄送: JJins ***@***.***>; State change ***@***.***>
主题: Re: [wy580477/PaaS-vmess-trojan-argo] 可以设置仅ipv4吗？ (Issue #5)


After switching to tunnel+vm, it is very stable and has never been broken again. It has nothing to do with v6, that’s why

Then try to use the cloudflared tunnel. If it continues, it may be that the http routing of the azure web app entry has restrictions on the long-term connection of the websocket.

Are you using it on render? Is it working?

―
