### ISSUE TITLE
使用 Northflank Dockerfile方式部署 后台报错

### ISSUE THREAD

**Issue by valetzx** [wy580477/PaaS-vmess-trojan-argo#6]
F Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle': /workdir/Caddyfile:2 - Error during parsing: Wrong argument count or unexpected line ending after 'valetzx/vm*'

**Comment by wy580477** [comment]
Which branch did you use?

**Comment by valetzx** [comment]
main at https://github.com/pigeonpig/main-north

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/224467451-05a7ee25-8c8a-4a34-a528-1a58af25cc7c.png)
切了分支也有同样报错

**Comment by wy580477** [comment]
无法复现。是不是变量设置有问题。

![image](https://user-images.githubusercontent.com/98247050/224467696-70c6ffd6-353d-4524-8887-2510f13f4c52.png)
![image](https://user-images.githubusercontent.com/98247050/224467698-2a7d89eb-b18e-43fc-b6b0-6f721134ec5b.png)

**Comment by valetzx** [comment]
![image](https://user-images.githubusercontent.com/45054400/224467752-7e24521f-00ac-48bb-9674-2ff744da203c.png)这是我的环境变量

**Comment by wy580477** [comment]
> 这是我的环境变量

路径格式是 /xxxxx

**Comment by valetzx** [comment]
好的谢谢
