### ISSUE TITLE
有没有办法走全局warp？

### ISSUE THREAD

**Issue by dinaau** [wy580477/PaaS-vmess-trojan-argo#8]
并且用v2rayN的客户端

**Comment by wy580477** [comment]
有，临时办法是连接 yacd 面板，可以选择 warp 出站，但容器重启后会失效。

永久办法是，改下 content/config.json , "final": "Select" 改成 "final": "WARP"

**Comment by wy580477** [comment]
> 并且用v2rayN的客户端

![image](https://user-images.githubusercontent.com/98247050/236627000-5f839214-4eed-41cf-b58e-a03cf46a8d93.png)

wgvm 和 wgtr 结尾的路径，就是全局 WARP

**Comment by dinaau** [comment]
> 

在fly.io 上测试了下， vmess正常
但是切换到wgvm结尾的路径就连不上了

配置用的都是你首页默认的配置， 自己没有自定义任何变量或额外添加

**Comment by wy580477** [comment]
> 在fly.io 上测试了下， vmess正常 但是切换到wgvm结尾的路径就连不上了
> 
> 配置用的都是你首页默认的配置， 自己没有自定义任何变量或额外添加

使用 WARP 出站，需要自己准备一个 warp 配置文件，使用里面的密钥设置相关变量后才能用。

**Comment by dinaau** [comment]
> > 在fly.io 上测试了下， vmess正常 但是切换到wgvm结尾的路径就连不上了
> > 配置用的都是你首页默认的配置， 自己没有自定义任何变量或额外添加
> 
> 使用 WARP 出站，需要自己准备一个 warp 配置文件，使用里面的密钥设置相关变量后才能用。

可以详细的说明一下吗，这个配置文件有模板吗，文件要放在哪个路径下面

**Comment by wy580477** [comment]
> 可以详细的说明一下吗，这个配置文件有模板吗，文件要放在哪个路径下面

用这个项目注册：

https://github.com/badafans/warp-reg

然后根据得到的密钥值设置 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 变量。

注意 HK 地区应该还需要保留字段，我没考虑到，一定要用HK地区的话，得自己看看sing-box文档，修改 config-wg.json 文件加上保留字段。

**Comment by dinaau** [comment]
加进去了 不是HK地区的

但是仍然连不上warp 😭

![](https://s3.tebi.io/github/2023-05-07_00-40-08.jpg)

**Comment by wy580477** [comment]
血压上来了，README真是白写了。我让你用环境变量，为啥你去直接改配置文件。

**Comment by dinaau** [comment]
> 血压上来了，我让你用环境变量，为啥你去直接改配置文件。

fly.io 这个只能在本地编辑好配置文件 然后才能push到server

**Comment by wy580477** [comment]
> fly.io 这个只能在本地编辑好配置文件 然后才能push到server

那说明你不会写 fly.toml 文件。

参照这个：

https://github.com/wy580477/Mosdns-on-PaaS/blob/main/fly.toml

**Comment by dinaau** [comment]
> > fly.io 这个只能在本地编辑好配置文件 然后才能push到server
> 
> 那说明你不会写 fly.toml 文件。
> 
> 参照这个：
> 
> https://github.com/wy580477/Mosdns-on-PaaS/blob/main/fly.toml

请指正如果我有理解错误

你的意思是要把 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 这2个变量写道fly.toml里

所以得到的是这样，对吗

[env]
  DOH_PATH = "/dns-query"

[[services]]
  internal_port = 8080
  protocol = "tcp"
WG_PRIVATE_KEY="6GUxxxx"
WG_PEER_PUBLIC_KEY="bmxxxxxx"
 

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "120s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

**Comment by wy580477** [comment]
> 请指正如果我有理解错误
> 
> 你的意思是要把 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 这2个变量写道fly.toml里
> 
> 所以得到的是这样，对吗


忘了 fly.toml 文件吧。我没精力教你怎么写 toml 配置文件。

直接改 config-wg.json 文件，改名成 config.json 。原来的 config.json 删掉。

**Comment by dinaau** [comment]
> > 请指正如果我有理解错误
> > 你的意思是要把 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 这2个变量写道fly.toml里
> > 所以得到的是这样，对吗
> 
> 忘了 fly.toml 文件吧。我没精力教你怎么写 toml 配置文件。
> 
> 直接改 config-wg.json 文件，改名成 config.json 。原来的 config.json 删掉。

重新部署了一遍， vmess 跟wgvm 都不通了

**Comment by wy580477** [comment]
帮不上了，不好意思。

**Comment by wy580477** [comment]
> 你的意思是要把 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 这2个变量写道fly.toml里

昨晚躺床上手机没法搓配置文件，今天写了一份，如果看不懂我也没办法，随缘吧。

https://github.com/wy580477/PaaS-vmess-trojan-argo/blob/main/fly.toml

**Comment by dinaau** [comment]
> > 你的意思是要把 WG_PRIVATE_KEY 和 WG_PEER_PUBLIC_KEY 这2个变量写道fly.toml里
> 
> 
> 
> 昨晚躺床上手机没法搓配置文件，今天写了一份，如果看不懂我也没办法，随缘吧。
> 
> 
> 
> https://github.com/wy580477/PaaS-vmess-trojan-argo/blob/main/fly.toml
> 
> 
> 
> 
> 
> 

实在感谢 close了issue 都放弃了没想到会有更新 现在也在手机上 粗略看了下 能看懂 明天再试一下

**Comment by dinaau** [comment]
有个很奇怪的问题就是全局warp的时候经常会断流
用的不是热门地区， 不知道是不是跟配置有关还

![2023-05-08_-43-42](https://user-images.githubusercontent.com/68769882/236753847-fe8667e6-a5c3-4da5-9870-79a7c4c31b2b.jpg)

**Comment by wy580477** [comment]
> 有个很奇怪的问题就是全局warp的时候经常会断流 用的不是热门地区， 不知道是不是跟配置有关还

可能是默认的 mtu 值需要调整一下，看下面的链接里面有配置格式：

https://sing-box.sagernet.org/configuration/outbound/wireguard/#structure

我 google 出来的结果是 mtu 设置低了会报这个错误。
